name: conda-parser
channels:
  - defaults
dependencies:
  - black
  - conda
  - coverage
  - flask
  - gunicorn
  - libiconv
  - nginx
  - pip
  - pytest
  - pytest-mock
  - pytest-cov
  - python=3.7.4
  - pyyaml
  - yaml
  - pip:
    - pytest-flask
